/// <reference types="Cypress" />

export default {
    
//Seletores página de login
campoUsuarioLogin: '#user',
campoSenhaLogin: '#pass',
botaoEntrarLogin: '#entrarButton',
errorLoginIncorreto: '#alert-dialog-slide-description',
inputMatriculaRecuperarSenha: 'input[name="userMatricula"]',
inputCPFRecuperarSenha: 'input[name="userCPF"]',

//Seletores do módulo de consulta da cadeia de custódia
moduloCadeiaDeCustodia: ':nth-child(2) > .MuiStep-root > .MuiButtonBase-root',
moduloConsultaDeVestígios: '.css-ixpjxk > .MuiPaper-root',
tituloConsultaVestigios: '.mod-title',
dataInicialConsulta: '#\\:re\\:',
dataFinalConsulta: '#\\:rf\\:',
botaoPesquisarConsulta: '.MuiBox-root > .MuiButton-root',
numeroLacreConsulta: '#\\:rg\\:',
codigoRastreamentoConsulta: '#\\:rh\\:',
nomeResponsavelPreservacaoConsulta: '#\\:ri\\:',
matriculaResponsavelPreservacaoConsulta: '#\\:rj\\:',
nomeResponsavelColetaConsulta: '#\\:rk\\:',
matriculaResponsavelColetaConsulta: '#\\:rl\\:',
botaoLimparCampos: '.css-15j76c0 > .MuiButton-root',
botaoVisualizarVestigio: '[aria-label="Visualizar"]',

//Seletores da visualização de um vestígio
checkboxSimAmbienteIsoladoVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section/div[1]/div/div/div/label[1]/span[1]/input',
checkboxNaoAmbienteIsoladoVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section/div[1]/div/div/div/label[2]/span[1]/input',
checkboxSimAmbientePreservadoVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section/div[2]/div/div/div/label[1]/span[1]/input',
checkboxNaoAmbientePreservadoVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section/div[2]/div/div/div/label[2]/span[1]/input',
localizacaoVisualizacaoVestigio: '#localizacao',
matriculaResponsavelPreservacaoVisualizacao: '#matricula',
nomeResponsavelPreservacaoVisualizacao: 'input[name="nome"]',
nomeResponsavelPreservacaoVisualizacao2: "#\\:r12\\:",
cargoResponsavelPreservacaoVisualizacao: '#cargo',
unidadeResponsavelPreservacaoVisualizacao: 'input[name="unidade"]',
unidadeResponsavelPreservacaoVisualizacao2:  '#\\:r14\\:',
dataChegadaResponsavelPreservacaoVisualizacao: 'input[placeholder="dd/mm/aaaa"]',
dataChegadaResponsavelPreservacaoVisualizacao2: '#\\:r15\\:',
horaChegadaResponsavelPreservacaoVisualizacao: 'input[placeholder="hh:mm"]',
horaChegadaResponsavelPreservacaoVisualizacao2: '#\\:r16\\:',
botaoProximoVisualizacao1: '.MuiButton-containedPrimary',
matriculaResponsavelColetaVisualizacao: '#matriculaColeta',
nomeResponsavelColetaVisualizacao: 'input[name="nomeColeta"]',
nomeResponsavelColetaVisualizacao3: '#\\:r18\\:',
cargoResponsavelColetaVisualizacao: '#selCargo',
unidadeResponsavelColetaVisualizacao: 'input[name="unidadeColeta"]',
nidadeResponsavelColetaVisualizacao2: '#\\:r1a\\:',
checkboxImediatoPosicaoVestigioVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section[2]/div[1]/div/div/div/label[1]/span[1]/input',
checkboxMediatoPosicaoVestigioVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section[2]/div[1]/div/div/div/label[2]/span[1]/input',
checkboxRelacionadoPosicaoVestigioVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section[2]/div[1]/div/div/div/label[3]/span[1]/input',
descPosicaoVestigioVisualizacao: '#descPosicao',
numeroVestigioVisualizacao: '#nvest',
numeroLacreVisualizacao: '#primeiroLacre',
dataColetaPosicaoVestigioVisualizacao: 'input[placeholder="dd/mm/aaaa"]',
horaColetaPosicaoVestigioVisualizacao: 'input[placeholder="hh:mm"]',
campoVestigiosVisualizacao: '.MuiGrid-grid-md-3 > .MuiPaper-root',
olhoCampoVestigiosVisualizacao: '.MuiGrid-grid-xs-12 > .MuiButtonBase-root',
checkboxQntdAproximadaVisualizacao: '/html/body/div[2]/div[3]/div/div[2]/div/div[1]/label/span[1]/input',
tipoDeVestigioModalVisualizacao: '/html/body/div[2]/div[3]/div/div[2]/div/div[2]/div/div/div',
subTipoVestigioModalVisualizacao: '/html/body/div[2]/div[3]/div/div[2]/div/div[3]/div/div/div',
qntdTipoVestigioModalVisualizacao: '/html/body/div[2]/div[3]/div/div[2]/div/div[4]/div/div/input',
unidadeMedidaTipoVestigioModalVisualizacao: '/html/body/div[2]/div[3]/div/div[2]/div/div[5]/div/div/div',
fechaModalTipoVestigioVisualizacao: '/html/body/div[2]/div[3]/div/h2/button',
descricaoVestigioVisualizacao: '.MuiGrid-grid-md-9 > .MuiFormControl-root > .MuiOutlinedInput-root',
checkboxSimNaturezaExameVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section[3]/div[2]/div/div/div/label[1]/span[1]/input',
checkboxNaoNaturezaExameVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section[3]/div[2]/div/div/div/label[2]/span[1]/input',
botaoProximoVisualizacao2: '.MuiButtonGroup-root > :nth-child(2)',
tipoProcedimentoRelacionadoVisualizacao: '.MuiDataGrid-row > [data-field="procedimento_tipo"]',
numeroProcedimentoRelacionadoVisualizacao: '.MuiDataGrid-row > [data-field="procedimento_numero"]',
unidadeProcedimentoRelacionadoVisualizacao: '.MuiDataGrid-row > [data-field="procedimento_unidade_nome"]',
autoridadeProcedimentoRelacionadoVisualizacao: '.MuiDataGrid-row > [data-field="procedimento_autoridade_nome"]',
botaoExcluirProcedimentoRelacionadoVisualizacao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[5]/div/button',
nomeResponsavelColetaVisualizacao2: '#\\:r12\\:',
unidadeResponsavelColetavisualizacao2: 'input[name="unidadeColeta"]',
dataColetaPosicaoVestigioVisualizacao2: '#\\:r19\\:',
horaColetaPosicaoVestigioVisualizacao2: '#\\:r1a\\:',
tipoDeVestigioModalVisualizacao2: '#\\:r1g\\:',
subtipoVestigioModalVisualizacao2: '#\\:r1h\\:',
qntdTipoVestigioModalVisualizacao2: '#\\:r1i\\:',
unidadeMedidaTipoVestigioModalVisualizacao2: '#\\:r1j\\:',
modeloTipoVestigioVisualizacao: '#\\:r1l\\:',
fechaModalTipoVestigioVisualizacao2: '#\\:r1f\\: > .MuiButtonBase-root',

//Seletores da página de Registro de Vestígios
moduloRegistroVestigios: '/html/body/div/div[3]/div/div/div[2]/div/div/div[2]/div[2]/div',
dropDownOrigemColeta: '/html/body/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div[1]/div/div',
listaDropDownOrigemColeta: '/html/body/div[2]/div[3]/ul',
campoLocalizacaoRegistroVestigio: '#localizacao',
campoResponsavelColetaRegistro: 'input[name="nomeColeta"]',
campoUnidadeColetaRegistro: 'input[name="unidadeColeta"]',
checkboxImediatoRegistro: 'input[type="radio"][value="Imediato"]',
botaoAdicionarVestigioRegistro: '/html/body/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div[5]/div[2]/div/div/div/section[3]/div[1]/div/div[1]/div',
dropDownTipoVestigioRegistro: '/html/body/div[2]/div[3]/div/div/div/div[2]/div/div/div',
listaDropDownTipoVestigioRegistro: '/html/body/div[3]/div[3]',
botaoSalvarTipoVestigioRegistro: '/html/body/div[2]/div[3]/div/div/div/div[6]/button',
campoDescricaoVestigioRegistro: '#descVest',
checkboxCriminalNaturezaExameRegistro: 'input[type="radio"][value="Criminal"]',
campoTipoProcedRelacionadoRegistro: '/html/body/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div[5]/div[2]/div/div/div/section/div/div[1]/div/div',
listaDropDownProcedRelacionadoRegistro: '/html/body/div[2]/div[3]/ul',
numeroProcedRelacionadoRegistro: '#numProced',
unidadeProcedRelacionadoRegistro: '/html/body/div[1]/div[3]/div/div/div[2]/div[2]/div[2]/div/div[5]/div[2]/div/div/div/section/div/div[2]/div[2]/div/div/input',
autoridadeProcedRelacionadoRegistro: 'input[name="autoridadeProcedimento"]',
naoDesejaRegistrarOutroVestigio: '/html/body/div[2]/div[3]/div/div[2]/button[2]',
botaoMeusVestigios: '/html/body/div/div[3]/div/div/div[2]/div[2]/button',
botaoLiberarVestigio: '[aria-label="Liberar"]',
simLiberarVestigio: '/html/body/div[2]/div[3]/div/div/div/div[2]/button',
checkboxDocNaoApresentado: 'input[name="apresentado_apresentou"]',
campoNomeApresentante: '#nome_apresentante',
campoEnderecoApresentante: 'input[name="apresentado_endereco"]',
campoLocalColetaEntregaTerceiros: '#local_coleta',
campoLocalEntrega: 'input[name="local_entrega"]',
observacoesColetaEntregaPorTerceiros: '#observacoes',
checkboxNaoAmbienteIsolado: 'input[name="isolamento"][value="NÃO"]',
checkboxSimAmbienteIsolado: 'input[name="isolamento"][value="SIM"]',
justificativaNaoIsolamento: '#justificativa',
checkboxSimAmbientePreservado: 'input[name="preservacao"][value="SIM"]',
checkboxNaoAmbientePreservado: 'input[name="preservacao"][value="NÃO"]',
secaoResponsavelPreservacaoLocal: '.css-duoaty',
justificativaNaoPreservacao: '#justificativaPreserva',
obsPreservacaoLocal: '#obs_preserva',
matriculaResponsavelColetaRegistroDPT: '#matriculaColeta',
nomeResponsavelColetaRegistroDPT: 'input[name="nomeColeta"]',
cargoResponsavelColetaRegistroDPT: 'input[name="cargoColeta"]',
unidadeResponsavelColetaRegistroDPT: 'input[name="unidadeColeta"]',
botaoSalvarRascunho: 'button[aria-label="Salvar este vestígio como rascunho"]',
modalRascunhoSalvoSucesso: '#dialogVestigio',
okModalRascunhoSalvo: '/html/body/div[2]/div[3]/div/div[2]/button',
codigoRastreamentoRegistroVestigio: '/html/body/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div[5]/div[1]/div[1]/h6[2]',
botaoMeusRascunhosRegistro: '/html/body/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div[2]/button',
botaoCancelarRascunho: 'button[aria-label="Cancelar o preenchimento"]',
simModalCancelarVestigio: '/html/body/div[2]/div[3]/div/div[2]/button[1]',

// Seletores da página de edição de vestígio
cardsVestigiosEdicao: 'div[class="MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-1k2lr4q"]',
botaoEdicaoVestigio: 'button[aria-label="Editar"]',
botaoLiberacaoVestigio: '[aria-label="Liberar"]',
moduloEdicaoDeVestigios: '/html/body/div/div[3]/div/div/div[2]/div/div/div[2]/div[3]/div',
tipoAditamentoEdicao: '/html/body/div[2]/div[3]/div/div/div/div[1]/button',
botaoAdicionarVestigioEdicao: '.MuiGrid-grid-md-3 > .MuiPaper-root',
campoTipoVestigioEdicao: '/html/body/div[2]/div[3]/div/div[2]/div/div[2]/div/div/div',
modalVestigioEditadoSucesso: '#dialogVestigio',
okModalVestigioEditado: '.MuiDialogActions-root > .MuiButton-root',
campoCodigoRastreamentoEdicao: 'input[name="rastreamento"]',
cardVestgioEdicao: '/html/body/div/div[3]/div/div/div[2]/div/div[2]/div/div/section[3]/div[1]/div/div[1]/div',
cardSituacaoVestigio: '/html/body/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div[2]/div/button/div[4]',

// Seletores da página de liberação de vestígios
moduloLiberacaoVestigios: '/html/body/div/div[3]/div/div/div[2]/div/div/div[2]/div[5]/div',
campoLacreConsultaEdicao: 'input[name="lacre"]',
iconeInfoLiberacaoVestigio: 'svg[data-testid="InfoIcon"]',
botaoSimLiberarVestigio: '.MuiDialogActions-root > :nth-child(1)',
dataInicialConsultaLiberacao: '/html/body/div/div[3]/div/div/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div/div/input',
dataFinalConsultaLiberacao: '/html/body/div/div[3]/div/div/div[2]/div[2]/div/div/div/div[1]/div[2]/div/div/div/input',
codRastreamentoConsultaLiberacao: 'input[name="rastreamento"]',
nomeRespPreservacaoConsultaLiberacao: 'input[name="nomePreservacao"]',
matriculaRespPreservacaoConsultaLiberacao: 'input[name="matriculaPreservacao"]',
nomeRespColetaConsultaLiberacao: 'input[name="nomeColeta"]',
matriculaRespColetaConsultaLiberacao: 'input[name="matriculaColeta"]',

// Seletores da página de transferência de vestígios
moduloTransferenciaVestigios: '/html/body/div/div[3]/div/div/div[2]/div/div/div[2]/div[4]/div',
botaoTransferirDetalhesVestigio: '/html/body/div[2]/div[3]/div/div/div[1]/div/div/div/button[2]',
campoInserirUnidadeTransferencia: '/html/body/div[2]/div[3]/div/div/div[3]/div/div[2]/div/div/div/input',
botaoTransferirVestigioFinal: '/html/body/div[2]/div[3]/div/div/div[3]/div/div[3]/button',
botaoReceberOpcoes: '/html/body/div/div[3]/div/div/div[2]/div[4]/div/table/tbody/tr[1]/td[4]/button',
botaoReceberDetalhesVestigio: '/html/body/div[2]/div[3]/div/div/div[1]/div/div/div/button[2]',
checkboxSimViolacaoRecebimento: '/html/body/div[2]/div[3]/div/div/div[3]/div/div[3]/div/div/div/label[1]/span[2]',
checkboxNaoViolacaoRecebimento: '/html/body/div[2]/div[3]/div/div/div[3]/div/div[3]/div/div/div/label[2]/span[2]',
campoDescrevaProblemasRecebimento: '/html/body/div[2]/div[3]/div/div/div[3]/div/div[4]/div/div/textarea[1]',
botaoReceberVestigioFinal: '/html/body/div[2]/div[3]/div/div/div[3]/div/div[4]/button'





}